quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
quarkus.http.auth.permission.search.paths=/search/v1*
quarkus.http.auth.permission.search.policy=authenticated
quarkus.http.auth.permission.fetch.paths=/search/v1*
quarkus.http.auth.permission.fetch.policy=authenticated
quarkus.http.auth.permission.comparison.paths=/comparison/v1*
quarkus.http.auth.permission.comparison.policy=authenticated
quarkus.http.auth.permission.oapi.paths=/q/openapi
quarkus.http.auth.permission.oapi.policy=permit